### ISSUE TITLE
Create Templates for Group Photo Post

### ISSUE THREAD

**Issue by KangkanS** [iGEM-Bettencourt-2021/Marketing-and-Communications#1]
Using Canva, create a few templates for the "Meet the Team" post for Instagram. The post will be two Instagram slides per person, one slide being a self-portrait on MS paint with a photoshopped selfie, the second being an information slide.

**Comment by research555** [comment]
Progress.

**Comment by KangkanS** [comment]
All templates have been created, they're all up on the shared drive. Awesome work @Sophlei  !!
