### ISSUE TITLE
Linkedin page: first post (w/ Julian & Jean)

### ISSUE THREAD

**Issue by ghost** [iGEM-Bettencourt-2021/Marketing-and-Communications#15]

**Comment by research555** [comment]
@jeanrannou @JulianQ22  Whats the update on this?

**Comment by jeanrannou** [comment]
@research555 meeting at 9:30 tonight to post it !

**Comment by ghost** [comment]
Update on yesterday's meeting: [here](https://docs.google.com/document/d/1q1_zNhFGQHKEMkCyju8wo1n8hnfIkS6LCu4NMtmTvL4/edit)
