### ISSUE TITLE
Create Team Logo

### ISSUE THREAD

**Issue by KangkanS** [iGEM-Bettencourt-2021/Marketing-and-Communications#4]
After the team project is selected, a team logo should be created soon after.  Should include Paris Bettencourt and maybe some elements of the project chosen (ex. if the project involves bacteria, the logo looks like one). 

File format: transparent png preferred,

**Comment by JulianQ22** [comment]
We will need 2 logos : 
+ **1 for Bettencourt** (sustainable throughout time, i.e. can be reused by the following Bettencourt iGEM teams). **We need that one SOON** ! _The insta current one is too ugly to remain on our account really_...
This logo should **integrate the classical iGEM logo** as the other teams do
+ **1 for the minicells project topic**

**Comment by git-cgalan** [comment]
![bettecourt7](https://user-images.githubusercontent.com/73339181/114470447-34304600-9bef-11eb-85b3-7b589f42da5d.png)
After adapting the last year general team logo I end up with this proposal. I will collect your opinion on the discord

**Comment by research555** [comment]
@Sophlei How is the minicells logo going?
