### ISSUE TITLE
Contacting igem teams 

### ISSUE THREAD

**Issue by KangkanS** [iGEM-Bettencourt-2021/Marketing-and-Communications#5]
Everyone should attempt to contact at least two teams a week. Ask them about any initiatives or events they're working on and if they need help.  Feel free to contact them using email, Paris-Bett Instagram, etc. Teams are split up by continent. 

Americas:
@ReidyPlayerOne 
@KangkanS 

Europe:
@JulianQ22 
@jeanrannou 
@Sophlei 

Asia:
@KaroGu 
@git-cgalan 
@AbhayKoushik 

Reminder: Contact teams from 2019/2020 first!

**Comment by research555** [comment]
Where are the results from this? It's been over a week. @AbhayKoushik @jeanrannou @KangkanS @git-cgalan @KaroGu @Sophlei @JulianQ22 @ReidyPlayerOne You need to report on your progress, I've explained this many times. Please review the general team flow chart. We can't keep having the same conversation.

**Comment by AbhayKoushik** [comment]
Hey, 

A meeting with iGEM Indian Institute of Science ([IISc](https://en.wikipedia.org/wiki/Indian_Institute_of_Science)) team has been set up on the calendar - scheduled on 4th April Sunday from 4 to 5 pm IST, feel free to join in and ask any questions on behalf of our team!

Meeting Link: https://meet.google.com/qki-rmhx-bbu

Cheers,
Abhay

PS: IISc is ranked 2nd in the world for citations per faculty by QS.

**Comment by ghost** [comment]
A meeting with iGEM University of Paris team had been scheduled on the 6th of April. 
We'll probably organize another meeting later this semester :)
