### ISSUE TITLE
Create a workflow for April 

### ISSUE THREAD

**Issue by KangkanS** [iGEM-Bettencourt-2021/Marketing-and-Communications#9]
A flowchart including the posts for Instagram, TikTok, Twitter, and uploads for the podcast. Should be broken down weekly with a clear objective and adequate detail

**Comment by research555** [comment]
Progress?

**Comment by KangkanS** [comment]
Workflow was completed on March 29th. Here is the link to the chart! 

https://lucid.app/lucidchart/invitations/accept/6fd87ac5-aff9-4385-9245-d1d343ecf7ca?viewport_loc=-461%2C-236%2C3152%2C1256%2C0_0
